server:
  port: ${HTTP_SERVER_PORT:5055}
spring:
  profiles:
    active: dev
  application:
    name: rasa-client
  datasource:
    password: Sql@1234
    url: jdbc:mysql://localhost:3306/rasadb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect